import type { Metadata } from "next";
import { Open_Sans, Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";

// --- Fonts ---

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout — fonts, global styles, and Redux provider for all pages
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${openSans.className} ${inter.className} h-full antialiased`}
    >
      <body className="flex flex-col min-h-full">
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
